version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user_password
      - MYSQL_DATABASE=employment_db
      - MYSQL_ROOT_PASSWORD=root
  #    volumes:
#      -
  nginx:
    image: nginx
    ports:
      - "80:80"
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app